[package]
name    = "bitcrab"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true

[[bin]]
name = "bitcrab"
path = "src/main.rs"

[dependencies]
bitcrab-common.workspace     = true
bitcrab-net.workspace        = true
bitcrab-node.workspace       = true
tokio.workspace              = true
clap.workspace               = true
tracing.workspace            = true
tracing-subscriber.workspace = true