[package]
name           = "bitcrab-common"
description    = "Bitcoin primitive types"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true

[lib]
path = "lib.rs"

[dependencies]
sha2.workspace      = true
ripemd.workspace    = true
sha1.workspace      = true
hex.workspace       = true
thiserror.workspace = true
tokio.workspace     = true
tracing.workspace   = true
serde.workspace     = true
